### ISSUE TITLE
_filename is not defined

### ISSUE THREAD

**Issue by liu1083947028** [jitsi/jitsi-meet-react#21]
download and unzip jitsi-meet-react.zip,and execute 'npm install'.

when i run in xcode, it tells me "_filename is not defined".

what i need to do?

thanks

![image](https://cloud.githubusercontent.com/assets/7359403/16373019/7a5f0eb2-3c82-11e6-8d80-1a2d775b7176.png)

**Comment by tsareg** [comment]
Hi, thanks for reporting! We're aware of this bug and working towards fixing it.

**Comment by lyubomir** [comment]
I don't get that after https://github.com/jitsi/jitsi-meet-react/commit/afbf167856668943b8e6ccc6677358aa522d4b9e so I'm closing this issue. Please re-open if it persists for you.
