### ISSUE TITLE
Phone is very hot

### ISSUE THREAD

**Issue by liu1083947028** [jitsi/jitsi-meet-react#38]
After a video, the phone will be very hot.

Can i get small resolution video stream to solve it?

and how can i get the specified resolution stream?

**Comment by lyubomir** [comment]
I acknowledge that a phone will generally become hot when sending & receiving audio & video.

Unfortunately, I find this issue to be lacking sufficient details to allow me to provide any answers. Which brand & model of phone gets hot? 'Small resolution video stream' for sending, receiving or both?

Anyway, please rephrase your questions to the dev mailing list with details.

**Comment by tsareg** [comment]
Even using phone's camera is a tough operation for mobile hardware. E.g. on iPhone 6 just launching local video gives about 30% CPU load. But we definitely need more details on the issue, as @lyubomir mentioned.
