### ISSUE TITLE
Question About Jitsi in Native

### ISSUE THREAD

**Issue by kononenko-a-m** [jitsi/jitsi-meet-react#54]
Hello,

Is there any possibility to use Jitsi as it is in native script environment without all other stuff?

Thanks,
Anton

**Comment by lyubomir** [comment]
I'm afraid I'm not sure what your asking. Please rephrase your question in an e-mail to the dev mailing lsit with more details such as explanations of which one of the many projects of the Jitsi community you're interested in & what you mean by 'native script environment'.

**Comment by tsareg** [comment]
As far as I understand, @kononenko-a-m means Native Script (https://www.nativescript.org/) - in some sort similar to React-Native framework for building mobile apps with JS.
The answer is - this project is about building UI for conference app with React-Native, but internally it uses lib-jitsi-meet - JS library for establishing connection to jitsi-videobridge and create conference. So you can use it and build your own custom UI with Native Script. You can find lib-jitsi-meet at https://github.com/jitsi/lib-jitsi-meet
