### ISSUE TITLE
Is Android support on the roadmap?

### ISSUE THREAD

**Issue by bryaneaton13** [jitsi/jitsi-meet-react#76]
I tried out the app on Android and initially got a blank screen.
After digging around a little bit, I noticed it was just a style issue. The `mirroredVideo` transform in the video styles is causing no video to display on Android.
https://github.com/jitsi/jitsi-meet-react/blob/master/features/base/media/components/native/styles/Styles.js#L15
You could put a Platform.OS check around that to not flip the video on Android.

Once I fixed that, I was able to see my local media, but I never saw my Android stream on the meet.jit.si website.

Is there Android support coming in the near future, or is there currently work happening on it?

Thanks,
Bryan

**Comment by tsareg** [comment]
Thanks for reporting that!
We're working on Android support.
