### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by kononenko-a-m** [jitsi/jitsi-meet-react#94]
Hello,

I try to test if app is working, but cannot build it on Android. 
But it fails with:

```
error: error reading /Users/Peter/work/jitsi-meet-react/android/app/build/intermediates/exploded-aar/jitsi-meet-react/react-native-webrtc/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in opening zip file
error: error reading /Users/Peter/work/jitsi-meet-react/android/app/build/intermediates/exploded-aar/jitsi-meet-react/react-native-webrtc/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in opening zip file
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:preDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDexDebug'.
> java.lang.RuntimeException: Exception while checking library jar
```

I can run with original react-native-webrtc from oney, but there some issues with creating local media tracks.

Maybe I need some global installed tool, in order to omit this build issue?

Thanks!

**Comment by lyubomir** [comment]
Please make sure to properly and fully install Git LFS as described at https://git-lfs.github.com/ and then run npm install --force react-native-webrtc.

**Comment by kononenko-a-m** [comment]
I have installed git LFS and tried `npm install --force react-native-webrt`
Same result. 

It's look like libjingle_peerconnection.so.jar recognized as corrupted :(

**Comment by lyubomir** [comment]
Did you execute `git lfs install` at least once before `npm install --force react-native-webrtc`?

**Comment by peter-mach** [comment]
@lyubomir your suggestions have helped me fix the building issue. 

I've ended up reinstalling git lfs and doing `git lfs install` with `npm install --force react-native-webrtc`

**Comment by kononenko-a-m** [comment]
@lyubomir thanks! it helped!
just thought that `brew install git-lfs` would be enough.
