### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by kritlivesync** [jitsi/jitsi-meet-react#96]
deploy to android device use command **react-native run-android**  found this error 
who know about this problem or not?

```
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDexDebug'.
> java.lang.RuntimeException: Exception while checking library jar
```

**Comment by lyubomir** [comment]
I'm unable to reproduce this problem. Moreover, we have automatic builds that trigger upon each commit and they are fine.

**Comment by lyubomir** [comment]
You could make sure that Git LFS is installed correctly i.e. you've run `git lfs install` at least once. Afterwards, please clean the source directory from any npm and gradle artifacts such as node_modules and build directories that are not part of the source repository. Then run `npm install` again.
