### ISSUE TITLE
could not be run normally on android

### ISSUE THREAD

**Issue by qinyang1980** [jitsi/jitsi-meet-react#99]
I try to build react-native android/ios app and try it:
1. npm install (everything is installed ok)
2. react-native run-android (installed the APP on device success)
3. on android device, open the app.
   there are errors.

![screenshot_2016-10-19-11-22-08-071_org jitsi jitsi_meet_react](https://cloud.githubusercontent.com/assets/6745689/19504716/0262b208-95ef-11e6-936c-9ff74990396c.png)

Anyone can help me ?

**Comment by lyubomir** [comment]
We merged this repository into https://github.com/jitsi/jitsi-meet in an ongoing effort to consolidate our Web and mobile efforts. We henceforth consider this repository "read-only". Please navigate to https://github.com/jitsi/jitsi-meet.
